[pytest]
markers =
    exercise_group_1: Tests for Exercise Group "Design and Development of Automated Tests"
    exercise_2_1: Exercise 2.1 e-commerce workflow automation
    exercise_2_2: Exercise 2.2 DemoQA web tables pagination workflow
    exercise_3_1: Exercise 3.1 Progress Bar synchronization
    exercise_3_2: Exercise 3.2 Dynamic Properties
    exercise_4_1: Exercise 4.1 data-driven e-commerce workflow
